### ISSUE TITLE
Allow and use gormlike:"false" (inverse of TaggedOnly())

### ISSUE THREAD

**Issue by addshore** [survivorbat/gorm-like#1]
> TaggedOnly(): Will only change queries on fields that have the gormlike:"true" tag

It would be nice to also have the inverse of this, ie. a list of fields which can not have gormlike act on them, but by default it is allowed on fields.

**Comment by survivorbat** [comment]
That's a good one, would you suggest to have it on regardless of configuration? (Set("gormlike", false) is always obeyed)

**Comment by addshore** [comment]
For my personal use case I think having it on by default makes sense.

I guess something like this should also apply

> If you want a particular query to not be like-able, use .Set("gormlike", false). This works regardless of configuration.

So you can still override the general setting on a per-query basis?
(But I don't need that)

**Comment by survivorbat** [comment]
Feature added in [v0.0.6](https://github.com/survivorbat/gorm-like/releases/tag/v0.0.6)
